type: simpleevse
name: EVSE DIN
sample: |
  # http://evracing.cz/simple-evse-wallbox
  # either locally attached:
  device: /dev/ttyUSB0 # serial RS485 interface
  # or via TCP:
  uri: 192.0.2.2:502 # Modbus TCP converter address
