type: custom
name: Solarlog (PV Meter)
sample: |
  power:
    source: modbus
    uri: 192.0.2.2:502 # IP address of the SolarLog  device and ModBus port address
    id: 1
    register:
      address: 3502
      type: input
      decode: uint32s
