type: custom
name: Fronius Solar API V1 (Battery Meter)
sample: |
  power:
    source: http
    uri: http://192.0.2.2/solar_api/v1/GetPowerFlowRealtimeData.fcgi
    jq: if .Body.Data.Site.P_Akku == null then 0 else .Body.Data.Site.P_Akku end
  soc:
    source: http
    uri: http://192.0.2.2/solar_api/v1/GetPowerFlowRealtimeData.fcgi
    jq: .Body.Data.Inverters."1".SOC
