type: custom
name: RCT Power Storage (Grid)
sample: |
  power:
    source: script
    cmd: /bin/bash -c "rctclient read-value --host 192.0.2.2 --name g_sync.p_ac_grid_sum_lp"
    timeout: 5s

# external application from https://github.com/svalouch/python-rctclient is required!