type: custom
name: Sonnenbatterie Eco/10 (Battery Meter)
sample: |
  power:
    source: http
    uri: http://192.0.2.2:8080/api/v1/status
    jq: .Pac_total_W
  soc:
    source: http
    uri: http://192.0.2.2:8080/api/v1/status
    jq: .USOC
